[tool.pytest.ini_options]
# TODO (0) fix paths and imports https://stackoverflow.com/questions/42996270/change-pytest-rootdir
pythonpath = ["german_active_vocab"]
filterwarnings = ["ignore::DeprecationWarning::"]
addopts = "-q --no-qt-log -p no:logging --show-capture=no"
qt_api="pyqt5"
qt_log_level_fail = "CRITICAL"
# "Individual warnings filters are specified as a sequence of fields separated by colons:"
# action:message:category:module:line
