[tool.pytest.ini_options]
# TODO (3) fix paths and imports and delete pythonpath here
# https://docs.pytest.org/en/latest/explanation/goodpractices.html#test-discovery
# https://docs.python-guide.org/writing/structure/
# https://dev.to/codemouse92/dead-simple-python-project-structure-and-imports-38c6
# https://stackoverflow.com/questions/42996270/change-pytest-rootdir
pythonpath = ["german_active_vocab"]
filterwarnings = ["ignore::DeprecationWarning::"]
addopts = "-q --no-qt-log -p no:logging --show-capture=no"
qt_api="pyqt5"
qt_log_level_fail = "CRITICAL"
# "Individual warnings filters are specified as a sequence of fields separated by colons:"
# action:message:category:module:line

# [tool.pylama]
# https://klen.github.io/pylama/#set-pylama-checkers-options
# ignore = "E501,W291"
# # https://klen.github.io/pylama/#command-line-options
# # format = "pylint"
# # linters = "pylint,mccabe"

# [tool.pylama.linter.pycodestyle]
# max_line_length = 120

[tool.pylint.messages_control]
extension-pkg-whitelist='PyQt5'
generated-members=['Qt.*', 'QTextCursor.*'] # desactivate no-member error
disable=[
    'logging-fstring-interpolation', # Performance thing: % is faster than f' ' for logging
    'missing-class-docstring',
    'missing-module-docstring',
    'missing-function-docstring',
    'import-error', # disable after using absolute imports
    'line-too-long',
    'trailing-whitespace',
    'fixme'
    ]
# e-length = 88
# disable = [
#   "missing-docstring",
#   "unused-argument",
#   "no-value-for-parameter",
#   "no-member",
#   "no-else-return",
#   "bad-whitespace",
#   "bad-continuation",
#   "line-too-long",
#   "fixme",
#   "protected-access",
#   "too-few-public-methods",
# ]